name: modbus_client_serial
description: This is the Modbus Client (ASCII and RTU) package sending requests to a remote device via Serial Port
version: 1.3.0
repository: https://github.com/gabireugabiru/modbus_client_serial
publish_to: none
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  logging: ^1.2.0
  libserialport: ^0.3.0+1
  synchronized: ^3.1.0
  modbus_client: 
    git:
      url: "https://github.com/gabireugabiru/modbus_client"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
